production:
  secret_token: 445337145466-kvq9slfidm3ca29jb7eeddlpkt09278i.apps.googleusercontent.com
  secret_key_base: xP_01l0NPd03-tQTciOQME_d
  google_id: 445337145466-kvq9slfidm3ca29jb7eeddlpkt09278i.apps.googleusercontent.com
  google_secret: xP_01l0NPd03-tQTciOQME_d
development:
  google_id: 445337145466-kvq9slfidm3ca29jb7eeddlpkt09278i.apps.googleusercontent.com
  google_secret: xP_01l0NPd03-tQTciOQME_d
  secret_token: 445337145466-kvq9slfidm3ca29jb7eeddlpkt09278i.apps.googleusercontent.com
  secret_key_base: xP_01l0NPd03-tQTciOQME_d
